import{a as L,i as u,S as y}from"./assets/vendor-BWuBPKg2.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const E="46068740-edf0cd65fcad07ce38acca64d",v="https://pixabay.com/api/",h=async(t,s=1)=>(await L.get(v,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data,m=t=>{document.getElementById("results").insertAdjacentHTML("beforeend",t.map(({webformatURL:a,largeImageURL:o,tags:e,likes:r,views:l,comments:g,downloads:b})=>`
        <li class="list-item">
            <a href="${o}" class="gallery-item">
                <img src="${a}" alt="${e}" />
            </a>
            <div class="info">
                <span>Likes: ${r}</span>
                <span>Views: ${l}</span>
                <span>Comments: ${g}</span>
                <span>Downloads: ${b}</span>
            </div>
        </li>
    `).join(""))},f=()=>{document.getElementById("loading").style.display="block"},p=()=>{document.getElementById("loading").style.display="none"},i=t=>{u.error({title:"Error",message:t})},w=t=>{u.warning({title:"Attention",message:t})},I=()=>{document.getElementById("results").innerHTML=""};let c=1,d="";const x=document.querySelector("#searchForm"),n=document.createElement("button");n.textContent="Load more";n.style.display="none";n.classList.add("load-more-button");document.body.append(n);x.addEventListener("submit",async t=>{t.preventDefault();const s=document.getElementById("searchQuery"),a=s.value.trim();if(a===""){w("Fill this field!");return}d=a,c=1,I(),f();try{const o=await h(d,c);o.hits.length===0?(i("Sorry, there are no images matching your search query. Please try again!"),n.style.display="none"):(m(o.hits),new y(".gallery a").refresh(),n.style.display="block",o.totalHits<=15&&(n.style.display="none",i("We're sorry, but you've reached the end of search results.")))}catch(o){i("Щось пішло не так. Спробуйте ще раз."),console.error("Error fetching data:",o)}finally{p(),s.value=""}});n.addEventListener("click",async()=>{c+=1,f();try{const t=await h(d,c);t.hits.length===0?(n.style.display="none",i("We're sorry, but you've reached the end of search results.")):(m(t.hits),new y(".gallery a").refresh(),t.totalHits<=c*15&&(n.style.display="none",i("We're sorry, but you've reached the end of search results.")))}catch(t){i("Щось пішло не так. Спробуйте ще раз."),console.error("Error fetching data:",t)}finally{p()}});
//# sourceMappingURL=index.js.map
