import{a as L,i as u,S as y}from"./assets/vendor-BWuBPKg2.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const v="46068740-edf0cd65fcad07ce38acca64d",w="https://pixabay.com/api/",h=async(e,s=1)=>(await L.get(w,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data,m=e=>{document.getElementById("results").insertAdjacentHTML("beforeend",e.map(({webformatURL:a,largeImageURL:o,tags:t,likes:r,views:l,comments:p,downloads:b})=>`
        <li class="list-item">
            <a href="${o}" class="gallery-item">
                <img src="${a}" alt="${t}" />
            </a>
            <div class="info">
                <span>Likes: ${r}</span>
                <span>Views: ${l}</span>
                <span>Comments: ${p}</span>
                <span>Downloads: ${b}</span>
            </div>
        </li>
    `).join(""))},f=()=>{document.getElementById("loading").style.display="block"},g=()=>{document.getElementById("loading").style.display="none"},i=e=>{u.error({title:"Error",message:e})},E=e=>{u.warning({title:"Attention",message:e})},I=()=>{document.getElementById("results").innerHTML=""};let c=1,d="";const B=document.querySelector("#searchForm"),n=document.createElement("button");n.textContent="Load more";n.style.display="none";n.classList.add("load-more-button");document.body.append(n);B.addEventListener("submit",async e=>{e.preventDefault();const s=document.getElementById("searchQuery"),a=s.value.trim();if(a===""){E("Fill this field!");return}d=a,c=1,I(),f();try{const o=await h(d,c);o.hits.length===0?(i("Sorry, there are no images matching your search query. Please try again!"),n.style.display="none"):(m(o.hits),new y(".gallery a").refresh(),n.style.display="block",o.totalHits<=15&&(n.style.display="none",i("We're sorry, but you've reached the end of search results.")))}catch(o){i("Щось пішло не так. Спробуйте ще раз."),console.error("Error fetching data:",o)}finally{g(),s.value=""}});n.addEventListener("click",async()=>{c+=1,f();try{const e=await h(d,c);e.hits.length===0?(n.style.display="none",i("We're sorry, but you've reached the end of search results.")):(m(e.hits),new y(".gallery a").refresh(),x(),e.totalHits<=c*15&&(n.style.display="none",i("We're sorry, but you've reached the end of search results.")))}catch(e){i("Щось пішло не так. Спробуйте ще раз."),console.error("Error fetching data:",e)}finally{g()}});function x(){const e=document.querySelectorAll(".list-item");if(e.length>0){const s=e[e.length-1],{height:a}=s.getBoundingClientRect();window.scrollBy({top:a*3,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
